### ISSUE TITLE
Feature: Add support for iOS-driver capabilities

### ISSUE THREAD

**Issue by skyzyx** [Behat/MinkExtension#125]
Mink yells at me when I try to use some of the capabilities for iOS-driver in my behat.yml.

I looked around for documentation on writing my own definitions for things like this, but couldn't find any. Attempts to patch my own copy seem to be wrought with failure.

``` yml
iphone:
  context:
    class: IPhoneRunner
  extensions:
    Behat\MinkExtension\Extension:
      browser_name: iphone
      selenium2:
        wd_host: "http://127.0.0.1:5555/wd/hub"
        capabilities:
          browser: iphone
          browserName: iPhone
          deviceType: iphone
          platform: mac
          version: "7.1"
```

Capabilities are listed here: https://github.com/ios-driver/ios-driver/blob/dev/common/src/main/java/org/uiautomation/ios/IOSCapabilities.java#L43-L84
