### ISSUE TITLE
Adding tunnel-identifier capabilities parameter support for saucelabs configuration

### ISSUE THREAD

**Issue by m-naw** [Behat/MinkExtension#126]
```
default:
    extensions:       
        Behat\MinkExtension\Extension:
            default_session: saucelabs
            goutte: ~
            saucelabs:              
              username:
              access_key:
              browser: chrome
              capabilities: { platform: "Windows 7", version: 30, tunnel-identifier: xxx }
```
