### ISSUE TITLE
Unable to specify Selenium version in SauceLabsFactory

### ISSUE THREAD

**Issue by legovaer** [Behat/MinkExtension#139]
Hi Guys,

I'm facing difficulties while trying to specify the selenium version in the Saucelabs factory driver

My behat structure looks like this:

``` yaml
sauce:
  extensions:
    Behat\MinkExtension\Extension:
      default_session: saucelabs
      saucelabs:
        username: <myuname>
        access_key: <myapikey>
        capabilities:
          platform: "Windows 2012 R2"
          version: "34"
          name: "[Regression] Windows 2012 R2 chrome"
          selenium-version: "2.38.0"
```

But then I got the following error;
Unrecognized options "selenium_version" under "behat.extensions.behat_minkextension_extension.saucelabs.capabilities" 

Kind regards!
