### ISSUE TITLE
No method is configured to handle the ssl.certificate_authority config key (InvalidArgumentException)

### ISSUE THREAD

**Issue by j4m3s** [Behat/MinkExtension#165]
Has the mechanism for configuring goutte to ignore ssl cert errors changed?  After update from stable to dev-master (using composer) I'm now seeing the following error:
```No method is configured to handle the ssl.certificate_authority config key (InvalidArgumentException)```

behat.yml matches the docs in the repo:
```
    extensions:
        Behat\MinkExtension:
            sessions: 
                defaultHeadless: 
                    goutte:
                        guzzle_parameters:
                            ssl.certificate_authority: false
```

If I remove the ssl config setting altogether the tests won't run due to the curl ssl cert problem.

Thanks.

**Comment by KuenzelIT** [comment]
I had the same issue and stof's hint did lead me to the correct key, which is "verify" in Guzzle 5!

http://docs.guzzlephp.org/en/latest/clients.html#verify

**Comment by toin0u** [comment]
Have you solved this issue @j4m3s ?
@KuenzelIT is right. The correct `behat.yml`, in your case, looks like:

```yml
default:
    extensions:
        Behat\MinkExtension:
            sessions: 
                defaultHeadless: 
                    goutte:
                        guzzle_parameters:
                            verify: false
```

**Comment by j4m3s** [comment]
@toin0u I had to roll back to the version I was using before because of some other issues so didn't have to check it out any further (I'm still on the version using `ssl.certificate_authority: false`).  

I'm sure you're right though - closing this ticket, sorry for leaving it hanging.

**Comment by uptownhr** [comment]
Any update on this matter? I don't think should be closed as reverting back to a previous version is a fix. Here's my configs and error. 

```
//error
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\RequestException)
```


```
//composer.json
{
    "require": {
        "facebook/webdriver": "~1.1",
        "behat/mink": "^1.7",
        "behat/mink-goutte-driver": "^1.2"
    },
    "require-dev": {
        "behat/behat": "~3.0.4",
        "behat/mink-extension": "^2.1"
    },
    "scripts": {
	"behat": "behat"
    }
}
```

```
//behat.yml
default:
  extensions:
    Behat\MinkExtension:
      goutte:
        guzzle_parameters:
          verify: false
          ssl.certificate_authority: false
          curl.options:
            CURLOPT_SSL_VERIFYPEER: false
            CURLOPT_CERTINFO: false
            CURLOPT_TIMEOUT: 120

```
