### ISSUE TITLE
How to set a resolution param in behat.yml

### ISSUE THREAD

**Issue by Sorbing** [Behat/MinkExtension#167]
How to set the resolution (window size) param in behat.yml? I tried to do so:
```
default:
    extensions:
        Behat\MinkExtension:
            sessions:
                selenium2:
                    selenium2:
                        capabilities:
                            extra_capabilities:
                                resolution: 1280x1024
```
It's not works.
I need to set the resolution for the `phantomjs` session, because the default resolution is very small - `400x300`.
I can do this in the code (in the Context ) :
```
/**
 * @BeforeScenario
 */
public function beforeScenario(Behat\Behat\Hook\Scope\BeforeScenarioScope $scope)
{
    $this->getSession()->getDriver()->resizeWindow(1440, 900);
}
```
However, it would be convenient to change the resolution in the profile settings. Thanks.
P.S. I use Behat 3.0-dev.
