### ISSUE TITLE
`Behat\MinkExtension` extension file or class could not be located.

### ISSUE THREAD

**Issue by cdarken** [Behat/MinkExtension#168]
When I run behat I get the error in the title.

My relevant configuration sections:

composer.json require-dev:

```
"behat/behat": "~3.0.4",
"behat/mink": "~1.5.0",
"behat/mink-goutte-driver": "~1.0.9",
"behat/mink-extension": "2.0.*@dev",
```

composer.json psr-0 autoload:

```
"Mip\\Tests\\Behat": "app/tests/behat/features/bootstrap"
```

behat.yml:

```
default:
  suites:
    access:
      paths: [ %paths.base%/app/tests/behat/features ]
      contexts: 
        - Behat\MinkExtension\Context\MinkContext
        - Mip\Tests\Behat\RestrictedAccessContext
      filters:
        tags: @restricted-access
  extensions:
    Behat\MinkExtension:
      base_url: http://acdc-testing:8000
      goutte: ~
      selenium2: ~
```

What am I doing wrong?
Sorry if there is already explained somewhere, but I searched and I could not find a working solution.
