### ISSUE TITLE
[SauceLabs] Empty custom-data key causes tests not to run

### ISSUE THREAD

**Issue by dantleech** [Behat/MinkExtension#179]
If an empty `custom-data` key is sent to the server it prevents the tests from running.

i,e,

````
sauce_labs:
    extensions:
        Behat\MinkExtension:
            base_url: 'http://localhost:8000/'
            sessions:
                default:
                    sauce_labs:
                        username: sulu-cmf
                        access-key: xxx-xxx-xxx
````

Does not work.

The following actions made it work:

- Removing the `custom-data` parameter from [SauceLabsFactory](https://github.com/behat/MinkExtension/blob/master/src/Behat/MinkExtension/ServiceContainer/Driver/SauceLabsFactory.php#L69)
- Adding values to the field (e.g. `release: 1.0`)
