### ISSUE TITLE
Goutte Factory sending through wrong Guzzle config

### ISSUE THREAD

**Issue by catharsisjelly** [Behat/MinkExtension#230]
Hi there,

We have been using Mink for a while with our self cert SSL and after an upgrade via composer it's not not been working. Were currently running the following

* Mink 1.7.0
* Behat 3.0.15
* Mink Extension 2.1.0
* Mink Goutte Driver 1.2.0
* Guzzle 6

I found that I needed to change the configuration to my behat to be the following

```
default:
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            sessions:
                default:
                    goutte:
                        guzzle_parameters:
                            verify: false
```

So in theory everything should be fine but our self-cert is still being checked reguardless of what we tell Mink. After some digging we found that the parameter is not being passed through to Guzzle, the problem lies in `GoutteFactory` line 93 where it does

```php
return new Definition('GuzzleHttp\Client', array(array('defaults' => $parameters)));
```

The parameter being passed to Guzzle are being put one level deeper than they need to be. Now I find it hard to believe that the problem lies with this bit of code but it is the only real explanation. I have written a little bit of test code to try and prove it using Guzzle direct. The following fails

```php
$url = 'https://my.url.com';
$client = new GuzzleHttp\Client(['defaults' => ['verify' => false]]);
$var = $client->request('GET', $url);
```

Whereas this passes

```php
$url = 'https://my.url.com';
$client = new GuzzleHttp\Client(['verify' => false]);
$var = $client->request('GET', $url);
```

If I remove the extra layer in `GoutteFactory` e.g. 

```php
return new Definition('GuzzleHttp\Client', array($parameters));
``` 

Our SSL is skipped as expected. I'm still digging in the problem a bit but as the Mink driver and Guzzle are so widely used it feels very odd that I have to change `GoutteFactory` for this to work. Sorry for the wall of text but any help is appreciated
