### ISSUE TITLE
Anyone else having issues with session being lost on dev-master?

### ISSUE THREAD

**Issue by madeofsteel** [Behat/MinkExtension#247]
I have created a basic test that logs in the user via entering the login credentials, and clicking a login button. The next step where I need to click a menu item fails because of what looks like the session is not set. 

Also, why is
```php
$this->getSession
```
taken out in dev master branch? The programmer is now going to have to use a setter/getter to reuse the session through the lifecycle of the feature. Do we just change these major dependencies without any sort of a question? or documentation?

**Comment by aik099** [comment]
Can you please share your feature file?

**Comment by madeofsteel** [comment]
sure

```yaml
# behat.yml
default:
    extensions:
        Behat\MinkExtension:
            goutte: ~
            selenium2: ~
```
