### ISSUE TITLE
Does not correctly fill in form fields

### ISSUE THREAD

**Issue by nietzscheson** [Behat/MinkExtension#286]
I have a form, with two fields. Username and password. I did some tests with the admin | admin, for each field. If I change the value admin by administrator (or any other value other than admin) the fields are not filled. There are so many things involved that I do not know what is failing. I’m using everything in Homestead, PHP7. Behat, Mink, Selenium2. Quartz.

![behat-720](https://user-images.githubusercontent.com/1699198/28507713-a1fc9546-6ffa-11e7-8df9-54f985c7a243.gif)

```feature
Feature: Login

  @javascript
  Scenario: Login
    Given I am on the homepage
    When I fill in "_username" with "administrador"
    And I fill in "_password" with "administrador"
    When I press "_submit"
```
```yml

default:
    formatters:
        pretty:
            verbose: true
            paths: false
            snippets: false

    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: "http://sisfc.app/app_test.php/"
            default_session: symfony
            javascript_session: chrome
            sessions:
                symfony:
                    symfony2: ~
                chrome:
                    selenium2:
                        browser: chrome
                        capabilities:
                            browserName: chrome
                            browser: chrome
                            version: ""
                            chrome:
                                switches:
                                    - "start-fullscreen"
                                    - "start-maximized"
                                    - "no-sandbox"
                firefox:
                    selenium2:
                        browser: firefox
            show_auto: false
```
```yml
default:
    suites:
        default:
            contexts:
                - DefaultContext
```
```php
<?php

use Behat\MinkExtension\Context\MinkContext;

class DefaultContext extends MinkContext
{
}
```
