### ISSUE TITLE
Selenium2: Firefox is launched with browser_name: chrome since the latest release

### ISSUE THREAD

**Issue by ArthurHoaro** [Behat/MinkExtension#309]
The latest release includes this change in `Selenium2Factory` which for some reason makes Selenium run Firefox instead of Chrome.

```php
+   ->booleanNode('marionette')->defaultFalse()->end()
```

Config:

```yml
default:
  extensions:
    Behat\MinkExtension:
      browser_name: chrome
      selenium2:
        wd_host: "http://172.17.0.1:4444/wd/hub"
        capabilities:
          chrome:
            switches:
              - "--disable-gpu"
              - "--headless"
```

Selenium log **with** the mentioned change:

> Capabilities {browser: firefox, browserName: chrome, chrome.extensions: [], chrome.switches: [--disable-gpu, --headless, --window-size=1920,1080, --whitelisted-ips=""], chromeOptions: {args: [--disable-gpu, --headless, --window-size=1920,1080, --whitelisted-ips=""], extensions: []}, ignoreZoomSetting: false, **marionette: false**, name: Behat feature suite, tags: [php, PHP 5.6.31]} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.**firefox.XpiDriverService**)

Selenium log **without** the mentioned change:

> Capabilities {browser: firefox, browserName: chrome, chrome.extensions: [], chrome.switches: [--disable-gpu, --headless, --window-size=1920,1080, --whitelisted-ips=""], chromeOptions: {args: [--disable-gpu, --headless, --window-size=1920,1080, --whitelisted-ips=""], extensions: []}, ignoreZoomSetting: false, name: Behat feature suite, tags: [php, PHP 5.6.31]} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.**chrome.ChromeDriverService**)

**Comment by paulgibbs** [comment]
My project's also run into what seems to be the same problem. On Travis-CI, using this alongside Behat and Selenium, without Firefox installed, we see a "Could not open connection: Timed out waiting 45 seconds for Firefox to start" error: https://travis-ci.org/paulgibbs/behat-wordpress-extension/jobs/308000669

Downgrading Behat/MinkExtension to `v2.2` resolved the issue for me.

**Comment by omordach** [comment]
I have the same problem after updating behat/mink-extension from `v2.2` to `v2.3.0`.

When I run tests Firefox is launched instead of Chrome and I got an error:
```
Could not open connection: Timed out waiting 45 seconds for Firefox to start.
      Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
      System info: host: 'oleg-15IAP', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-40-generic', java.version: '9.0.1'
      Driver info: driver.version: unknown (Behat\Mink\Exception\DriverException)
```

**Downgrading Behat/MinkExtension to` v2.2` resolved the issue.**

My behat.yml 
```
default:
    extensions:
        Laracasts\Behat: ~
        Behat\MinkExtension:
            default_session: laravel
            base_url: https://test.test/
            javascript_session: selenium2
            browser_name: chrome
            laravel: ~
            goutte: ~ 
            selenium2: ~
```

I'm using latest selenium-server-standalone-3.7.1 and Chromedriver=2.33.506092
