### ISSUE TITLE
Error with chrome: Could not open connection: Unable to create a new session because of no configuration.

### ISSUE THREAD

**Issue by dmaicher** [Behat/MinkExtension#310]
With version 2.3 I get this error for all my tests:

```
  ┌─ @BeforeScenario # FeatureContext::init()
  │
  ╳  Could not open connection: Unable to create a new session because of no configuration.
  ╳  Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
  ╳  System info: host: '93bc1e07047c', ip: '172.21.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-17-generic', java.version: '1.8.0_131'
  ╳  Driver info: driver.version: unknown (Behat\Mink\Exception\DriverException)
  │
```

I'm using the docker image `selenium/standalone-chrome:3.6.0` and this config:

```
    Behat\MinkExtension:
        base_url: http://...
        selenium2:
            wd_host: http://selenium:4444/wd/hub
        javascript_session: selenium2
        browser_name: chrome
```

Reverting to 2.2 solves the issue for me.

Other dependencies:

```
        {
            "name": "behat/transliterator",
            "version": "v1.2.0",
--
        {
            "name": "behat/behat",
            "version": "v3.4.3",
--
        {
            "name": "behat/gherkin",
            "version": "v4.5.1",
--
        {
            "name": "behat/mink",
            "version": "v1.7.1",
--
        {
            "name": "behat/mink-selenium2-driver",
            "version": "v1.3.1",
--
        {
            "name": "behat/symfony2-extension",
            "version": "2.1.2",
