### ISSUE TITLE
Browserstack: iPhone 7 not found

### ISSUE THREAD

**Issue by teewurst** [Behat/MinkExtension#317]
Not Sure why, but as soon as I try to do mobile testing, it tells me, that any device (iPhone 7, Samsung Galaxy S8 etc.) listed on browserstack could not be found. [https://www.browserstack.com/automate/capabilities](https://www.browserstack.com/automate/capabilities)

```
Could not open connection: Could not find device: iPhone 7 (Behat\Mink\Exception\DriverException)
```
My capabilities:
```
            browser_stack:
                capabilities:
                    browserstack-tunnel: true
                    acceptSslCerts: true
                    browserstack-debug: false
                    device: 'iPhone 7'
                    os_version: '10.3'
```

Other configurations like ...
```
                capabilities:
                    browserstack-tunnel: true
                    acceptSslCerts: true
                    browserstack-debug: false
                    os: Windows
                    os_version: '7'
                    browser: IE
                    browserVersion: '10'
```
... are working like charm. Only device does not work.

Does anybody know why? Is anything missing in my configuration?
