### ISSUE TITLE
Can MinkExtension be used to include a Chrome extension into Selenium2?

### ISSUE THREAD

**Issue by mashiox** [Behat/MinkExtension#319]
I am attempting to use Behat+Mink+Selenium to test my web application, but, I cannot figure out how MinkExtension can be leveraged to configure Selenium/ChromeDriver to include a Chrome extension into a browser configuration.

I have modified my `behat.yml` to reflect the Chrome options I would like to run under
```yml
extensions:
    Behat\MinkExtension\Extension:
      selenium2:
        browser: chrome
        capabilities:
          browserName: "chrome"
          chromeOptions:
            extensions:
                - "/usr/src/test/chromeExtensionDirectory"
```

However, when I execute Behat, it exits with the following exception
```
In ExtensionManager.php line 194:
                                                                                 
  [Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]   
  `Behat\MinkExtension\Extension` extension file or class could not be located.
```

As far as I can tell, I am using the latest stable versions of Behat and Mink, with Selenium 3.4 standalone.
This is my `composer.json`
```json
{   
    "require": {       
        "behat/mink": "1.6.@stable",       
        "behat/mink-extension": "@stable",       
        "behat/mink-goutte-driver": "@stable",       
        "behat/mink-selenium2-driver": "@stable",
        "bossa/phpspec2-expect":"1.*",
        "sauce/sausage": "0.17.0",   
	"sauce/connect": ">=3.0",	
        "sensiolabs/behat-page-object-extension": "*"

    },   
   "config": {       
     "bin-dir": "bin/"   
   },
    "require-dev": {
        "behat/behat": "^3.2",
        "emuse/behat-html-formatter": "^0.1.0",
        "jakub-onderka/php-parallel-lint": "^1.0.0"
    }
}
```

Please excuse me if I'm using any wrong verbiage. I am new to Selenium testing, as well as Behat and Mink.
