### ISSUE TITLE
Specify session name to get

### ISSUE THREAD

**Issue by kochen** [Behat/MinkExtension#321]
When using in combination with `Behat/MinkExtension` and setting the `Symfony cache`:
```
        Behat\MinkExtension:
            sessions:
                default:
                    symfony: ~
```

you get:
```
Specify session name to get  
```

setting other sessions like `goutte` (and its corresponding driver) results in the same issue.

**Comment by kochen** [comment]
For reference: https://github.com/FriendsOfBehat/SymfonyExtension/issues/30

**Comment by kochen** [comment]
Same issue with `Behat/Symfony2Extension`

**Comment by loic425** [comment]
@everzet @stof any news about this error ? I've got same error on sf4.1

**Comment by kochen** [comment]
Manage to narrow it down to [prepareDefaultMinkSession](https://github.com/Behat/MinkExtension/blob/master/src/Behat/MinkExtension/Listener/SessionsListener.php#L83) (namely `setDefaultSessionName`) not being called and therefor `default session` not being set, so when calling `getSession($name=null)` it won't find any default session.

**Comment by kochen** [comment]
@stof 
```
<service id="mink.default_session" class="Behat\Mink\Session" lazy="true" public="false">
    <factory service="__behat__.mink" method="getSession" />
</service>
```

```
        Behat\MinkExtension:
            base_url: "http://localhost:8080/"
            default_session: symfony
            sessions:
                symfony:
                    symfony: ~
```
