### ISSUE TITLE
How to use with CrossBrowserTesting?

### ISSUE THREAD

**Issue by bartonhammond** [Behat/MinkExtension#324]
CrossBrowserTesting (CBT) has this [https://github.com/crossbrowsertesting/selenium-php-behat3](https://github.com/crossbrowsertesting/selenium-php-behat3) example.

How would I update my `extension` to work w/ CBT?

Here's my yml:
```                  
  extensions:
    Behat\MinkExtension:
      browser_name: 'chrome'
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: http://0.0.0.0:4444/wd/hub
        capabilities: { "browser": "chrome", "version": "", 'chrome': {'switches':['--start-maximized']}}
      #base_url: https://www.twlw.dev
      base_url: twlw.wpengine.com
```

**Comment by bartonhammond** [comment]
I've added  **CrossBrowserTestingFactory.php** (CBT) and updated `MinkExtension.php` appropriately.  

I don't see the test running on CBT. 

Should I create a branch?

I get error
**Error**
```
In ParameterBag.php line 100:
  The service "mink.listener.sessions" has a dependency on a non-existent parameter "mink.default_session".  
```
**feature**
```
Feature: Home
  In order to navigate the site
  As a visitor
  I want to test navigation

  Background:
    Given I reset "all" data
    Given I am a visitor
    When I go to the "Home" page
    And I take a screenshot "home page"

  @javascript 
  Scenario: I can see multiple links 
    Then I should see "Programmes" link 
    And I should see "How It Works" link 
    And I should see "Self-Help/Resources" link 
    And I should see "Try It Free" link
    And I take a screenshot "Home page"    
```

**behat.yml**
```
default:
  suites:
    default:
      paths: ["%paths.base%/features/temp/home.feature"]
      local_screenshots: false      
      contexts: [ThinkWellContext]

  extensions:
    Behat\MinkExtension:
      sessions:
        my_session:
          cross_browser_testing:
            server: "crossbrowsertesting.com"
            user: "bh@wisnet.com"
            key: "u00d"
            capabilities: 
              name: "Wisnet - ThinkWell"
              build: "1.0.0"
              os_api_name: "Mac10.12"
              browser_api_name: "Chrome62x64"
              resolution: "1920x1200"
              record_video: "true"
              record_network: "true"
              max_duration: "14400"
              browser: "Chrome"
      base_url: twlw.wpengine.com
      
    SensioLabs\Behat\PageObjectExtension:
      namespaces:
        page: [Page]
        element: [Page]
```

**CrossBrowserTestingFactory.php**
```
<?php

/*
 * This file is part of the Behat MinkExtension.
 * (c) Konstantin Kudryashov <ever.zet@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Behat\MinkExtension\ServiceContainer\Driver;

use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;

class CrossBrowserTestingFactory extends Selenium2Factory
{
    /**
     * {@inheritdoc}
     */
    public function getDriverName()
    {
        return 'cross_browser_testing';
    }

    /**
     * {@inheritdoc}
     */
    public function configure(ArrayNodeDefinition $builder)
    {
        $builder
            ->children()
                ->scalarNode('user')->defaultValue(getenv('CROSSBROWSERTESTING_USERNAME'))->end()
                ->scalarNode('key')->defaultValue(getenv('CROSSBROWSERTESTING_ACCESS_KEY'))->end()
                ->scalarNode('server')->defaultValue('crossbrowsertesting.com')->end()            
                ->scalarNode('browser')->defaultValue('chrome')->end()
                ->append($this->getCapabilitiesNode())
            ->end()
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function buildDriver(array $config)
    {
        $config['wd_host'] = sprintf('%s:%s@%s/wd/hub', $config['user'], $config['key'], $config['server']);
        return parent::buildDriver($config);
    }

    protected function getCapabilitiesNode()
    {
        $node = parent::getCapabilitiesNode();
        $node
            ->children()
                ->scalarNode('os_api_name')->end()
                ->scalarNode('browser_api_name')->end()
                ->scalarNode('resolution')->end()
                ->scalarNode('name')->end()
                ->scalarNode('build')->end()
                ->scalarNode('record_video')->end()
                ->scalarNode('record_network')->end()
                ->scalarNode('max_duration')->end()
            ->end()
        ;
        return $node;
    }
}

```

**Comment by bartonhammond** [comment]
I updated my yml and now get different error:

**Error**

```
 Background:                           # features/temp/home.feature:6
    Given I reset "all" data            # ThinkwellContext::iResetData()
      │ Reset Post Data
      │ Reset User Program Data
      │ Reset User Data
      │ 
    Given I am a visitor                # ThinkwellContext::iAmAVisitor()
    When I go to the "Home" page        # ThinkwellContext::iGoToThePage()
      Expected to be on "https://twlw.wpengine.com/" but found "" instead (SensioLabs\Behat\PageObjectExtension\PageObject\Exception\UnexpectedPageException)
    And I take a screenshot "home page" # ThinkwellContext::iTakeAScreenshot()
```

**behat.yml**
```
default:
  suites:
    default:
      paths: ["%paths.base%/features/temp/home.feature"]
      local_screenshots: false      
      contexts: [ThinkWellContext]

  extensions:
    Behat\MinkExtension:
      browser_name: 'chrome'
      base_url: https://twlw.wpengine.com      
      default_session: cross_browser_testing  ###### this line added
      cross_browser_testing:
        server: "crossbrowsertesting.com"
        user: "bhammond@wisnet.com"
        key: "u0459a8738c4a60d"
        capabilities: 
          name: "Wisnet - ThinkWell"
          build: "1.0.0"
          os_api_name: "Mac10.12"
          browser_api_name: "Chrome62x64"
          resolution: "1920x1200"
          record_video: "true"
          record_network: "true"
          max_duration: "14400"
          browser: "Chrome"

      
    SensioLabs\Behat\PageObjectExtension:
      namespaces:
        page: [Page]
        element: [Page]
```
