### ISSUE TITLE
How to read wd_host from behat.yml

### ISSUE THREAD

**Issue by bartonhammond** [Behat/MinkExtension#328]
Is it possible to get access to the `wd_host` parameter?  My context implements `MinkAwareContext` and when the function `setMink(Mink $mink)` is called I tried getting the session `selenium2` but could not determine how to get the `wd_host` parameter.  I need to know if I am running in the cloud or locally.

```
  extensions:
    Behat\MinkExtension:
      default_session: selenium2
      browser_name: chrome
      base_url: https://twlwtest.wpengine.com               
      selenium2:
        #wd_host: http://localhost:4444/wd/hub
        wd_host: https://name:password@crossbrowsertesting.com/wd/hub
        capabilities:
          name: "TWLW"
          extra_capabilities:
```
