### ISSUE TITLE
"base_url" conflict between symfony driver and zombie driver

### ISSUE THREAD

**Issue by arnaugm** [Behat/MinkExtension#33]
I'm creating scenarios which some use the default symfony driver and some others that need javascript use the zombie driver.
I have had to create the app_test.php file and write the full path to it in the "base_url" option of the extension to make the zombie test work.
But then the scenarios that use the symfony driver use the "base_url" too to build the routes and of course, these don't exist. I'm I missconfigurating something?

**Comment by slootjes** [comment]
Sorry to bump an old issue but I think this is better than creating a new one since I think my issue is exactly the same. When I run my tests with goutte or selenium2 driver it works great but when testing with symfony2 driver it will internally use the baseurl and go to "http://localhost/my_project/htdocs/" while this should simply be "/". Maybe someone can point out what is wrong with my config or maybe this bug got back somehow.

behat.yml
```
default:
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: http://localhost/my_project/htdocs/
            browser_name: firefox
            default_session: symfony2
            sessions:
                goutte:
                    goutte: ~
                selenium2:
                    selenium2: ~
                symfony2:
                    symfony2: ~
    suites:
        front_end:
            type: symfony_bundle
            bundle: AppFrontEndBundle
            contexts:
                - App\FrontEndBundle\Features\Context\FeatureContext:
```

Versions:
Symfony: 2.8.4
Behat: 3.1.0
Mink: 1.7.1
Mink Extension: 2.2
Mink BrowserKit Driver: 1.3.2
Mink Symfony2 Extension: 2.1.1

Let me know if more info is needed.
