### ISSUE TITLE
fillField failing for good "field"

### ISSUE THREAD

**Issue by crossan007** [Behat/MinkExtension#345]
Seeing a weird issue when running ChromeDriver 75, Behat 3.5.0, MinkExtension 2.3.1.   

Every call to `MinkContext::fillField` fails because  `Behat\Mink\Element::findAll` returns null, and I get an `ElementNotFoundException`.  

I took a look at the generated xPath, and it looked really over-complicated(but might still have been valid).   

I don't see anything in the selenium console logs to indicate a failed "find", but I'm not sure it would show there anyway.

Any pointers where to dig deeper?

**Comment by SirPL** [comment]
I'm similar issue which may be related to this one – the `$page->getContent()` returns valid HTML code, but `$page->find('css', 'html')` returns `null`. The same occurs for every other valid tag and id.

**Comment by crossan007** [comment]
yes; `$page->getContent()` does return the DOM

**Comment by crossan007** [comment]
I reverted my Chrome browser from Version 75 to Version 74, and also reverted my version of ChromeDriver.exe, and the problem appears to have gone away.

It would appear that something in the upgrade from Chrome 74 to Chrome 75 (or ChromeDriver) causes this issue

**Comment by crossan007** [comment]
I seem to get this error on Firefox 68 with GeckoDriver as well.

Still digging in to see if I can figure out the culprit.

**Comment by crossan007** [comment]
I think this is documented as in issue in the GeckoDriver repository: https://github.com/mozilla/geckodriver/issues/1581

It's odd that it seems to affect both Chrome and Firefox equally

**Comment by crossan007** [comment]
Ah ha.  I think I uncovered some more details here. 

It looks like, starting with Chrome 75, the selenium mode defaults to w3c, and the MinkSelenium2Driver is considering switching from instaclick/php-webdriver to facebook/php-webdriver, but is holding off because of PHP7 support: https://github.com/minkphp/MinkSelenium2Driver/issues/293#issuecomment-499405228

**Comment by crossan007** [comment]
And a solution! (Or at least a temporary workaround):

In the thread above, they suggested *turning off W3C mode for chrome*.

So, adding that to my `behat.yml` file, I get this (note the `extra_capabilities`, `chromeOptions`, `w3c:false`)
```
default:
  suites:
        default:
            contexts:
                - nwcontext:form
                - nwcontext:formstone
                - nwcontext:select2
                - FeatureContext
  extensions:
    Novaway\CommonContexts\Extension: ~
    Behat\MinkExtension:
      base_url: http://localhost/crm
      selenium2:
        browser: chrome
        capabilities:
          browserName: "chrome"
          extra_capabilities:
            chromeOptions:
              w3c: false
```
