### ISSUE TITLE
I would like to use MinkContext in two different Context.

### ISSUE THREAD

**Issue by mtopcu** [Behat/MinkExtension#348]
I would like to use MinkContext in FeatureContext and other Context named as ApiContext. but When I try to use, I got below error.

Is there anyone who solved this issue? Thanks. 

Step "the response should be json" is already defined in FeatureContext::theResponseShouldBeJson()

My FeatureContext class like:  _class FeatureContext extends MinkContext_
My ApiContext class like:  _class ApiContext extends FeatureContext implements Context_

And my behat yml is like:
```
default:
  suites:
    default:
      contexts:
        - FeatureContext:
            parameters:
        - ApiContext:
            parameters:

  extensions:
    Behat\MinkExtension:
      base_url: http://api-v2-int.somc.io/
      browser_name: chrome
      default_session: default
      javascript_session: selenium2
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false
        selenium2:
          selenium2:
            wd_host: http://127.0.0.1:4444/wd/hub
            capabilities: {browserVersion:  , version:  }
```
