### ISSUE TITLE
[HELP] How do I configure selenium2 host url?

### ISSUE THREAD

**Issue by leonardoraele** [Behat/MinkExtension#372]
I'm running my selenium instance and behat in separate docker containers. By default, [behat/mink-selenium2-driver](https://packagist.org/packages/behat/mink-selenium2-driver) tries to connect to selenium on `localhost:4444`, so it won't work, but it does [allow you to configure the selenium host](https://github.com/minkphp/MinkSelenium2Driver/blob/master/src/Selenium2Driver.php#L76). How do I configure this in my `behat.yml` though? I didn't find how to do it in the doc.

**Comment by leonardoraele** [comment]
Ok, so I just went through the code and found my answer in the [Selenium2Factory:84](https://github.com/Behat/MinkExtension/blob/master/src/Behat/MinkExtension/ServiceContainer/Driver/Selenium2Factory.php#L84), it receives a `wd_host` property, so my `behat.yml` is like this now and it's working:

```yml
default:
  extensions:
    Behat\MinkExtension:
      sessions:
        default:
          selenium2:
            browser: chrome
            capabilities: []
            wd_host: http://selenium:4444/wd/hub
```
