### ISSUE TITLE
Disable SSL checks in Goutte

### ISSUE THREAD

**Issue by kevinsperrine** [Behat/MinkExtension#47]
I keep getting SSL errors when attempting to test my login functionality.

```
When I follow "Login"                                # FeatureContext::clickLink()
      [curl] 60: SSL certificate problem, verify that the CA cert is OK. Details:
      error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed [url]
```

I've tried adding the curl parameters to the sessions/goutte.xml file, but I'm not sure I'm doing it correctly. 

I've added the following, but I'm still getting errors. Can someone tell me to proper way to accomplish this? I've looked through the Guzzle Docs and found [this page](http://guzzlephp.org/tour/http.html?highlight=ssl) explaining how to pass parameters to guzzle, but the XML doesn't seem to be working as expected.

```
        <parameter key="behat.mink.goutte.guzzle_parameters" type="collection">
            <parameter key="curl.options" type="collection">
                <parameter key="CURLOPT_SSL_VERIFYPEER">false</parameter>
                <parameter key="CURLOPT_CERTINFO">false</parameter>
            </parameter>
            <parameter key="ssl.certificate_authority">false</parameter>
        </parameter>
```

**Comment by pelletiermaxime** [comment]
What worked for me with behat 3/mink 1.6 :
```yaml
  extensions:
    Behat\MinkExtension:
      goutte:
        guzzle_parameters:
          verify: false
```

**Comment by kvdnberg** [comment]
It seems thing changed slightly in Guzzle 5
Behat3/MinkExtension2.2

```
  extensions:
    Behat\MinkExtension:
      base_url: 'https://localhost'
      sessions:
        default:
          goutte:
            guzzle_parameters:
              defaults:
                verify: false
```

**Comment by ifdattic** [comment]
This worked for me:

```yaml
default:
    extensions:
        Behat\MinkExtension:
            base_url: https://localhost
            sessions:
                default:
                    goutte:
                        guzzle_parameters:
                            verify: false
```

It's the same as by @kvdnberg just without nesting under `defaults`.

Guzzle 6.2.2 / Behat 3.3.0 / MinkExtension 2.2
