### ISSUE TITLE
guzzle_options does not seem to work anymore for disabling curl SSL checks

### ISSUE THREAD

**Issue by chanind** [Behat/MinkExtension#67]
I used to use the following behat.yml to disable SSL checks for goutte:

``` yaml
        Behat\MinkExtension\Extension:
            goutte:
                guzzle_parameters:
                    curl.CURLOPT_SSL_VERIFYPEER: false
                    curl.CURLOPT_CERTINFO: false
```

However, since updating it seems that goutte is ignoring these settings and throwing the same SSL errors again. Is there a new syntax that needs to be used to work with the most recent version of goutte/mink?
