### ISSUE TITLE
The capability for firefox profile does not work

### ISSUE THREAD

**Issue by mandarille** [Behat/MinkExtension#92]
According to 'Extension.php' the profile should be specified as:

``` yaml
Behat\MinkExtension\Extension:    
      selenium2:
        capabilities: {'firefox': {'profile':'/path-to-zip'} }
```

The profile though doesn't get applied - instead webdriver creates an anonymous profile.
